"""Slice 019 (a) — BPMN→case bridge binding-resolution gate.

The BPMN `clearflow-ideal-incident-response` spawns the master crisis case via a
call activity whose `releaseKey` is bound to `Binding_MasterCrisisCase` in
`bindings_v2.json`. At solution-resolution time UiPath matches that binding's
`resourceKey` against a process **resource name** declared in the packed
solution (`resources/solution_folder/process/**/*.json` → `resource.name`) — NOT
against the caseplan's internal `name` field.

A binding whose `resourceKey` matches no solution resource is a *dangling*
binding: it packs and publishes fine, then silently fails to spawn at runtime.
This gate kills that whole class of bug — every BPMN binding must point at a
process resource the solution actually owns.

Authored RED against the Slice-018 state (`clearflow-crisis`, which matches no
resource); goes GREEN once retargeted to `clearflow-master-crisis`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
BPMN_BINDINGS = (
    REPO_ROOT
    / "maestro_bpmn"
    / "clearflow-ideal-incident-response"
    / "bindings_v2.json"
)
SOLUTION_PROCESS_DIR = (
    REPO_ROOT
    / "maestro_case"
    / "clearflow-solution"
    / "resources"
    / "solution_folder"
    / "process"
)


def _solution_process_resource_names() -> set[str]:
    """Every process `resource.name` the packed solution declares.

    These are the only keys a cross-project binding can resolve to.
    """
    names: set[str] = set()
    for manifest in SOLUTION_PROCESS_DIR.rglob("*.json"):
        data = json.loads(manifest.read_text(encoding="utf-8"))
        name = data.get("resource", {}).get("name")
        if name:
            names.add(name)
    return names


def _bpmn_process_bindings() -> list[dict]:
    """The `kind: process` resources declared in the BPMN bindings file."""
    data = json.loads(BPMN_BINDINGS.read_text(encoding="utf-8"))
    return [r for r in data.get("resources", []) if r.get("kind") == "process"]


# The committed solution registration that the *deploy* resolves against. It is
# NOT regenerated by pack-solution.sh (it is a `uip solution project add`
# artifact), so it can drift from the canonical binding and silently re-dangle
# the spawn at runtime — exactly the Slice-019 failure mode. Pin it here.
BPMN_REGISTRATION = (
    SOLUTION_PROCESS_DIR
    / "processOrchestration"
    / "ClearFlowIdealIncidentResponse.json"
)


def _registration_binding_types() -> list[str]:
    data = json.loads(BPMN_REGISTRATION.read_text(encoding="utf-8"))
    deps = data.get("resource", {}).get("runtimeDependencies", [])
    return [d.get("bindingType") for d in deps if d.get("bindingType")]


def test_solution_declares_the_master_case_resource() -> None:
    names = _solution_process_resource_names()
    assert "clearflow-master-crisis" in names, (
        "the packed solution must declare a process resource named "
        f"'clearflow-master-crisis'; found {sorted(names)}"
    )


def test_bpmn_has_at_least_one_process_binding() -> None:
    assert _bpmn_process_bindings(), (
        "the BPMN bindings file must declare the master-case process binding"
    )


@pytest.mark.parametrize("binding", _bpmn_process_bindings())
def test_bpmn_process_binding_resolves_to_a_real_resource(binding: dict) -> None:
    """`resourceKey` (and `resource`) must name a solution process resource.

    Compared with an optional leading dot stripped — caseplan spawns use the
    `.name` solution-relative form, the BPMN binding schema uses the bare name;
    either way the *resolved* key must be a real resource.
    """
    names = _solution_process_resource_names()
    for field in ("resourceKey", "resource"):
        raw = binding.get(field)
        assert raw, f"process binding {binding.get('id')!r} missing {field!r}"
        resolved = raw.lstrip(".")
        assert resolved in names, (
            f"BPMN binding {binding.get('id')!r} {field}={raw!r} resolves to no "
            f"solution process resource (dangling binding). Available: {sorted(names)}"
        )


def test_solution_registration_binding_resolves_to_a_real_resource() -> None:
    """The deploy-time `runtimeDependencies[].bindingType` must resolve too."""
    names = _solution_process_resource_names()
    types = _registration_binding_types()
    assert types, "BPMN registration declares no runtime binding dependency"
    for bt in types:
        assert bt.lstrip(".") in names, (
            f"solution registration bindingType={bt!r} resolves to no process "
            f"resource (deploy-time dangling binding). Available: {sorted(names)}"
        )


def test_registration_binding_matches_canonical_bpmn_binding() -> None:
    """The committed registration must not drift from the canonical bindings file.

    pack-solution.sh regenerates the project-content copy but NOT this
    registration; this assertion catches the drift that re-dangles the spawn.
    """
    canonical = {b.get("resource", "").lstrip(".") for b in _bpmn_process_bindings()}
    registered = {bt.lstrip(".") for bt in _registration_binding_types()}
    assert canonical == registered, (
        f"registration bindingType(s) {sorted(registered)} drifted from canonical "
        f"BPMN binding(s) {sorted(canonical)} — re-sync the registration manifest"
    )
