#!/usr/bin/env python3
"""Upsert the in-case audit-ledger-writer task into the master caseplan.

Idempotent patch (like scripts/merge-canvas-download.py): loads a
clearflow-master-crisis ``caseplan.json`` and ensures the **Closed** stage
(Stage_JW7OlW) holds one ``type:agent`` task invoking the deployed
``audit-ledger-writer`` LangGraph coded Agent, bound to ``case_ref =
metadata.caseId``, plus its two process/Agent bindings.

Why ``type:agent`` + an Agent (not a Coded Function): the Studio Web canvas only
resolves an Agent-type process to load its input schema and wire inputs; a coded
Function is not canvas-resolvable, so ``case_ref`` arrived empty and the job
faulted (verified live 2026-06-22). Re-expressed as a LangGraph Agent (the
forensic-self-exam pattern), the canvas wires ``case_ref`` and forwards it in-case.

Run BEFORE the canvas round-trip (on canonical) and again AFTER a canvas download
(on the extracted copy) so the task survives canvas regeneration:

    python3 scripts/add_audit_ledger_task.py                 # canonical master
    python3 scripts/add_audit_ledger_task.py /tmp/dl/<id>/.../caseplan.json

The compiled ``caseplan.json.bpmn`` is regenerated by the Studio Web canvas, not
here — see DEMO-RUNBOOK "Path B".
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CANONICAL = REPO_ROOT / "maestro_case" / "clearflow-master-crisis" / "caseplan.json"

CLOSED_STAGE_ID = "Stage_JW7OlW"
TASK_ID = "tALWdgr01"
NAME_BINDING_ID = "bALWnamE1"
FOLDER_BINDING_ID = "bALWfldP2"

# Two bindings — mirror the forensic LangGraph agent (resourceSubType "Agent");
# resourceKey "<folderPath>.<name>" with empty folderPath.
BINDINGS = [
    {
        "id": NAME_BINDING_ID,
        "name": "name",
        "type": "string",
        "resource": "process",
        "resourceSubType": "Agent",
        "resourceKey": ".audit-ledger-writer-langgraph",
        "default": "audit-ledger-writer-langgraph",
        "propertyAttribute": "name",
    },
    {
        "id": FOLDER_BINDING_ID,
        "name": "folderPath",
        "type": "string",
        "resource": "process",
        "resourceSubType": "Agent",
        "resourceKey": ".audit-ledger-writer-langgraph",
        "default": "",
        "propertyAttribute": "folderPath",
    },
]

# The agent task. case_ref binds to =js:metadata.caseId (input sinks need the
# =js: form). type:agent + an Agent-type process so the canvas wires the input.
TASK = {
    "id": TASK_ID,
    "type": "agent",
    "displayName": "Write Compliance Ledger",
    "elementId": f"{CLOSED_STAGE_ID}-{TASK_ID}",
    "isRequired": True,
    "shouldRunOnlyOnce": True,
    "data": {
        "name": f"=bindings.{NAME_BINDING_ID}",
        "folderPath": f"=bindings.{FOLDER_BINDING_ID}",
        "inputs": [
            {
                "name": "case_ref",
                "type": "string",
                "id": "vALWcsrf1",
                "var": "vALWcsrf1",
                "elementId": f"{CLOSED_STAGE_ID}-{TASK_ID}",
                "value": "=js:metadata.caseId",
            }
        ],
        "outputs": [],
    },
    "entryConditions": [
        {
            "id": "Condition_ALWent1",
            "displayName": "Stage entered",
            "rules": [[{"rule": "current-stage-entered", "id": "Rule_ALWent1"}]],
        }
    ],
}


def patch(path: Path) -> bool:
    """Upsert the bindings + task to the desired state. Returns True if changed."""
    doc = json.loads(path.read_text())
    changed = False

    bindings = doc.setdefault("bindings", [])
    by_id = {b.get("id"): b for b in bindings}
    for binding in BINDINGS:
        existing = by_id.get(binding["id"])
        if existing is None:
            bindings.append(dict(binding))
            changed = True
        elif existing != binding:
            existing.clear()
            existing.update(binding)
            changed = True

    closed = next((n for n in doc.get("nodes", []) if n.get("id") == CLOSED_STAGE_ID), None)
    if closed is None:
        raise SystemExit(f"Closed stage {CLOSED_STAGE_ID} not found in {path}")

    lanes = closed["data"].setdefault("tasks", [])
    found = False
    for lane in lanes:
        for i, t in enumerate(lane):
            if t.get("id") == TASK_ID:
                found = True
                if t != TASK:
                    lane[i] = dict(TASK)
                    changed = True
    if not found:
        lanes.append([dict(TASK)])  # own lane (FE layout only; entry condition drives run)
        changed = True

    if changed:
        path.write_text(json.dumps(doc, separators=(",", ":")))
    return changed


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    target = Path(args[0]) if args else CANONICAL
    if not target.exists():
        raise SystemExit(f"caseplan not found: {target}")
    changed = patch(target)
    print(f"{'patched' if changed else 'already current'}: {target}")
    print(f"  task {TASK_ID} (audit-ledger-writer, type:agent) in {CLOSED_STAGE_ID}; "
          f"bindings {NAME_BINDING_ID}/{FOLDER_BINDING_ID} (Agent)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
